title: Kiros-Blog-Theme
description: "A fork of hacker-blog for Kiro47's website"
author:
  name: "Someone"
  url: "https://ashishchaudhary.in/hacker-blog"
  email: "someone@somewebsite.somedomain"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Someone"
year : "2020"
